apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: booksservice
  name: booksservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: booksservice
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: booksservice
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:80
          image: alecaste18/bookservice:latest
          name: booksapp
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /root/.aspnet/https
              name: booksservice-claim0
              readOnly: true
            - mountPath: /root/.microsoft/usersecrets
              name: booksservice-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: booksservice-claim0
          persistentVolumeClaim:
            claimName: booksservice-claim0
            readOnly: true
        - name: booksservice-claim1
          persistentVolumeClaim:
            claimName: booksservice-claim1
            readOnly: true
status: {}
