version: '3.4'

services:

 customersservice:
    image: ${DOCKER_REGISTRY-}customersservice
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customersAPP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    ports:
      - "8002:80"