version: ‘3.4’

services:
 librarydb:
 container_name: librarydb
 restart: always
 volumes:
 — ${WEBAPP_STORAGE_HOME}/site:/data/db
 ports:
 — “27017:27017”

librimanager:
 container_name: librimanager
 environment:
 - ASPNETCORE_ENVIRONMENT=Development
 - “CatalogDatabaseSettings:ConnectionString=mongodb://librimanager:27017”
 depends_on:
 — librarydb
 volumes:
 - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
 - ${HOME}/.aspnet/https:/root/.aspnet/https/
 ports:
 — “8000:80”

web:
  build: .
  volumes:
    - '.:/code'
  ports:
    - 8883:80
  environment:
    DEBUG: 'true'

db:
  command: '-d'
  ports:
    - 5432:5432

cache:
  ports:
    - 6379:6379