version: '3.4'

services:
  booksapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "1818:443"
      - "1819:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro