version: '3.4'

services:
  db:
   image: "mcr.microsoft.com/mssql/server"
   environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=1Secure*Password1

  booksapi:
    image: ${DOCKER_REGISTRY-}booksapi
    ports:
      - "1818:443"
      - "1819:80"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - db