version: '3.4'

services:
  booksservice:
    image: "alecaste18/bookservice:latest"
    container_name: "BooksAPP"
    ports:
      - "1818:443"
      - "1819:80"
    depends_on:
     - booksdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80#https://+:443
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  booksdb:
   image: "mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04"
   container_name: "BooksDB"
   environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=yourStrong(!)Password5
   ports:
    - "1433:1433"
   volumes:
   - sqlserver_data:/var/opt/mssql
  
  borrowing-mongoDB:
    image: mongo:latest
    container_name: borrowingdb
    environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: borrowingdb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  borrowing_service:
    image: "alecaste18/borrowingservice:latest"
    container_name: borrowingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80#https://+:443  
    ports:
      - "3838:443"
      - "3839:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - borrowing-mongoDB
  
  customersservice:
    image: "alecaste18/customerservice:latest"
    container_name: customersAPP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80#https://+:443
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    ports:
      - "2828:443"
      - "2829:80"
  rabbitmq:
   image: "rabbitmq:3.9-management"
   container_name: "rabbitmq"
   ports:
    - "5672:5672"
    - "15672:15672"
    
volumes:
  sqlserver_data: {}
  mongodb_data: {}
   
