version: '3.4'

services:
  booksservice:
    image: ${DOCKER_REGISTRY-}booksservice
    container_name: "BooksAPP"
    ports:
      - "1818:443"
      - "1819:80"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - booksdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80  
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  booksdb:
   image: "mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04"
   container_name: "BooksDB"
   environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=yourStrong(!)Password5
   ports:
    - "1433:1433"
   volumes:
   - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: {}