version: '3.4'

services:
  db:
   image: "mcr.microsoft.com/mssql/server"
   environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=1Secure*Password1
   ports:
      - 1433:1433

  booksapi:
    image: ${DOCKER_REGISTRY-}booksapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - db