version: '3.4'

services:

 customersservice:
   container_name: customersapi
   environment:
      - ASPNETCORE_ENVIRONMENT=Development
   volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
   ports:
      - "2828:443"
      - "2829:80"