
name: fake_CD/CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1        
      - name: Build and push BooksService
        uses: docker/build-push-action@v2
        with:
          context: ./Services/Book/Book.API
          file: ./Services/Book/Book.API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bookservice:latest
    
  build-borrowing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1        
      - name: Build and push BooksService
        uses: docker/build-push-action@v2
        with:
          context: ./Services/Borrowings/BorrowingService
          file: ./Services/Borrowings/BorrowingService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/borrowingservice:latest
