name: Build And Push Nuget Package

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core Build Env
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0
    - name: Restore
      run: |
        pwd
        ls
        stat -c "%s"  Services/Customers/customersService/customersServiceTest/customersServiceTest.csproj
        dotnet restore Services/Customers/customersService/customersService.sln
    - name: UT
      run: dotnet test
