name: Tests

on: push

jobs: 
  tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: change folder and run test
        working-directory: library_microservice/Services/Customers/customersServiceTest
        run: dotnet test customersServiceTest.csproj
